#java
[language-server]
jdtls = { command = "jdtls" }
language-server = { command = "jdtls", args = [
  "-data", "/home/<USER>/.cache/jdtls/workspace"
  ]}

[[language]]
name = "java"
scope = "source.java"
injection-regex = "java"
file-types = ["java"]
roots = ["pom.xml", "build.gradle", ]
indent = { tab-width = 4, unit = "    " }
language-servers = [ "jdtls" ]




#latex
[language-server.texlab.config.texlab.build]
onSave = true




#JS and Ts
[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server", # optional
  "vscode-eslint-language-server",
]

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",




#Python
]
[[language]]
name = "python"
language-servers = [ "pyright" ]




#C
[[language]]
name = "c"
language-servers = ["clangd"]




#HTML
[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]



#lua
[[language]]
name = "lua"
language-servers = ["lua-language-server"]




#CSS
[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]




#Rust
[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format = true  

